# This is a basic workflow to help you get started with Actions

name: 'Creates PR'

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      build-hash:
        description: 'Build Hash'
        required: true
        default: 'latest'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-pr-to-deploy:
    name: Create PR To Deploy Code on Staging
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Deploy Raw Snapshot
        run: echo Deploying Raw Snapshot == ${{ github.event.inputs.build-hash }}!! >> deploy.txt

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy-stg-${{ github.event.inputs.build-hash }}
          force: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: deploy-stg-${{ github.event.inputs.build-hash }}
          branch: main
